<h1><?php echo $this->id; ?></h1>

<canvas id="<?php echo $this->id ?>" width="<?php echo $this->width ?>" height="<?php echo $this->height ?>"></canvas>
<script type="text/javascript">
    var ctx = document.getElementById('<?php echo $this->id ?>').getContext("2d");
    new Chart(ctx).<?php echo $this->chart->getType() ?>(
        <?php echo $this->chart->getData()->toJson() ?>,
        <?php echo $this->chart->getOptions()->toJson() ?>
    );
</script>